import Head from "next/head";

import MovieDetailsContainer from "@/containers/details";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const movieId = router.query;

  console.log({ movieId });

  return (
    <>
      <Head>
        <title>Movie Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieDetailsContainer />
    </>
  );
}
